"""Add past detections table

Revision ID: 470039492b66
Revises: c3a906464bb5
Create Date: 2025-03-08 07:42:47.728996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470039492b66'
down_revision = 'c3a906464bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_detection', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
